### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by klamarre21** [senchacredit/sencha-web#29]
Change Font to Open Sans

**Comment by klamarre21** [comment]
Change the major Font headings to Open Sans (Bold)
Smaller, Longer texts to Red Hat Display (Normal)

**Comment by klamarre21** [comment]
Change Header to "Empowering everyone (everyone in green) to reach new financial heights."

**Comment by klamarre21** [comment]
See if you can put a space in between the question mark here 
<img width="272" alt="Screen Shot 2021-01-08 at 1 38 12 PM" src="https://user-images.githubusercontent.com/74741577/104052331-8c524900-51b7-11eb-922f-995ce31360fb.png">

**Comment by klamarre21** [comment]
<img width="347" alt="Screen Shot 2021-01-08 at 1 39 10 PM" src="https://user-images.githubusercontent.com/74741577/104052387-a7bd5400-51b7-11eb-91a8-7afbff721673.png">
Change Font and add logo next to it

**Comment by klamarre21** [comment]
any way you could make this less visible?
<img width="270" alt="Screen Shot 2021-01-08 at 1 39 42 PM" src="https://user-images.githubusercontent.com/74741577/104052454-c15e9b80-51b7-11eb-8d99-f8cf5bb36924.png">

**Comment by klamarre21** [comment]
<img width="602" alt="Screen Shot 2021-01-08 at 1 40 29 PM" src="https://user-images.githubusercontent.com/74741577/104052513-d6d3c580-51b7-11eb-843d-c5573fe9a022.png">
Reduce wording take out the asteriks part, after that write "the debit card that builds credit. Spend hassle-free and we'll do all the work"

**Comment by andrewkirima** [comment]
> Change the major Font headings to Open Sans (Bold)
> Smaller, Longer texts to Red Hat Display (Normal)

I changed all the fonts but need to look into what Red Hat Display is like on Css.
